version: "3.4"
services:
  perlcryptblowfish:
    command: /usr/bin/rpmbuild -ba perl-Crypt-Blowfish.spec
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
  perlmd5:
    command: /usr/bin/rpmbuild -ba perl-MD5.spec
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
  perlmcrypt:
    command: /usr/bin/rpmbuild -ba perl-Mcrypt.spec
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.mcrypt

volumes:
  rpms:
    name: rpms
  rpm7:
    name: rpm7
