version: "3.4"
services:
  perlcryptblowfish:
    command: /usr/bin/rpmbuild -ba perl-Crypt-Blowfish.spec
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.crypt-blowfish
  perlmd5:
    command: /usr/bin/rpmbuild -ba perl-MD5.spec
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.md5
  perlmcrypt:
    command: /usr/bin/rpmbuild -ba perl-Mcrypt.spec
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.mcrypt
  perluuid:
    command: /usr/bin/rpmbuild -ba perl-UUID.spec
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.uuid

# Requires: perl-Socket6 >= 0.28
# Requires: perl-IO-Socket-INET6 >= 2.72

volumes:
  rpms:
    name: rpms
  rpm7:
    name: rpm7
